/*
 * This file is generated by jOOQ.
*/
package com.example.demo.jooq.domain;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_4AF602A7_CE7E_4888_B21C_BF4BEB1F8E1C</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_4AF602A7_CE7E_4888_B21C_BF4BEB1F8E1C = new SequenceImpl<Long>("SYSTEM_SEQUENCE_4AF602A7_CE7E_4888_B21C_BF4BEB1F8E1C", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);

    /**
     * The sequence <code>PUBLIC.SYSTEM_SEQUENCE_FADCFE88_5BCF_46FA_AB9F_038AAA5CBF25</code>
     */
    public static final Sequence<Long> SYSTEM_SEQUENCE_FADCFE88_5BCF_46FA_AB9F_038AAA5CBF25 = new SequenceImpl<Long>("SYSTEM_SEQUENCE_FADCFE88_5BCF_46FA_AB9F_038AAA5CBF25", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT);
}
